name: Auto-rebase Codex PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  rebase:
    # ne rebase que les PR internes dont la branche commence par "codex/"
    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'codex/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase on latest main (fallback merge)
        run: |
          set -e
          git fetch origin main
          set +e
          git rebase origin/main
          status=$?
          set -e
          if [ $status -ne 0 ]; then
            echo "Rebase conflict, fallback to merge"
            git rebase --abort || true
            git merge --no-edit origin/main || true
          fi

      - name: Push updated PR branch
        run: |
          git push --force-with-lease
