# .streamlit/config.toml

[theme]
base = "light"                 # force le mode clair
primaryColor = "#0B8A65"
backgroundColor = "#F7F4EB"    # fond page
textColor = "#111111"
font = "sans serif"
# optionnel, Streamlit accepte aussi :
# secondaryBackgroundColor = "#FFFFFF"

[browser]
gatherUsageStats = false       # pas de télémétrie

[server]
headless = true
address = "0.0.0.0"
port = 7860
enableCORS = true
enableXsrfProtection = true
