
# .streamlit/config.toml

[browser]
gatherUsageStats = false           # évite l’écriture du machine_id

[server]
headless = true
address = "0.0.0.0"
port = 7860
enableCORS = true
enableXsrfProtection = true
